### PR TITLE
fix build failures when using shared libraries

### LINKED ISSUE #220: 2021.08.28: Fails to link: error: undefined hidden symbol: rumur::parse(std::__1::basic_istream<char, std::__1::char_traits<char> >&)
```
ld: error: undefined hidden symbol: rumur::parse(std::__1::basic_istream<char, std::__1::char_traits<char> >&)
>>> referenced by main.cc
>>>               murphi2c/CMakeFiles/murphi2c.dir/src/main.cc.o:(main)

ld: error: undefined hidden symbol: rumur::resolve_symbols(rumur::Model&)
>>> referenced by main.cc
>>>               murphi2c/CMakeFiles/murphi2c.dir/src/main.cc.o:(main)

ld: error: undefined hidden symbol: rumur::validate(rumur::Node const&)
>>> referenced by main.cc
>>>               murphi2c/CMakeFiles/murphi2c.dir/src/main.cc.o:(main)

ld: error: undefined hidden symbol: rumur::sanitise_rule_names(rumur::Node&)
>>> referenced by main.cc
>>>               murphi2c/CMakeFiles/murphi2c.dir/src/main.cc.o:(main)
```

clang-11
FreeBSD 13

### PR DESCRIPTION
**Pull request by Smattr**
Fixes #220.

@yurivict the changes in this PR appear to fix the problems I've reproduced on macOS and FreeBSD. Can you confirm these changes fix things on your side too? If so, I'll merge this and then start the process for cutting a new release.

### CODE REVIEW

**Comment by yurivict** [comment]
It builds but all tests fail:
```
$ /usr/local/bin/python3.8 /disk-samsung/freebsd-ports/math/rumur/work/rumur-2021.08.28/tests/run-tests.py --verbose
test_193_2_py (__main__.executable) ... FAIL
test_comment_parsing_py (__main__.executable) ... skipped 'murphi-comment-ls not found'
test_lock_freedom_i386_py (__main__.executable) ... FAIL
test_lock_freedom_x86_64_py (__main__.executable) ... FAIL
test_murphi2murphi_decompose_array_py (__main__.executable) ... FAIL
test_murphi2murphi_decompose_record_py (__main__.executable) ... FAIL
test_murphi2murphi_explicit_semicolons_py (__main__.executable) ... FAIL
test_murphi2murphi_remove_liveness_py (__main__.executable) ... FAIL
test_murphi2murphi_switch_to_if1_py (__main__.executable) ... FAIL
test_murphi2murphi_switch_to_if2_py (__main__.executable) ... FAIL
```

**Comment by Smattr** [comment]
Thanks, Yuri. The command you're quoting is almost certainly expected to fail. None of the built binaries will be in your `$PATH`. The root CMake files does:

```cmake
add_custom_target(check
  COMMAND env PATH=${CMAKE_CURRENT_BINARY_DIR}/rumur:${CMAKE_CURRENT_BINARY_DIR}/murphi2c:${CMAKE_CURRENT_BINARY_DIR}/murphi2murphi:${CMAKE_CURRENT_BINARY_DIR}/murphi2uclid:${CMAKE_CURRENT_BINARY_DIR}/murphi2xml:${CMAKE_CURRENT_BINARY_DIR}/tests/murphi-comment-ls:$ENV{PATH}
    ${CMAKE_CURRENT_SOURCE_DIR}/tests/run-tests.py --verbose)
```

Can you try running `cmake --build . -- check` as CI does? Or alternatively prepend the command you're running with the `env` setup as is done in the CMake file?

**Comment by yurivict** [comment]
Tests pass now, thanks!

**Comment by Smattr** [comment]
Excellent!

**Pull request merged**
